openapi: 3.0.0
info:
  title: WooCommerce API Components
  version: '1.0.0'
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the resource.
          readOnly: true
        parent_id:
          type: integer
          description: Parent order ID.
        number:
          type: string
          description: Order number.
          readOnly: true
        order_key:
          type: string
          description: Order key.
          readOnly: true
        created_via:
          type: string
          description: Shows where the order was created.
          readOnly: true
        version:
          type: string
          description: Version of WooCommerce which last updated the order.
          readOnly: true
        status:
          type: string
          description: Order status.
          enum:
            - pending
            - processing
            - on-hold
            - completed
            - cancelled
            - refunded
            - failed
            - trash
          default: pending
        currency:
          type: string
          description: Currency the order was created with, in ISO format.
          default: USD
        date_created:
          type: string
          format: date-time
          description: The date the order was created, in the site's timezone.
          readOnly: true
        date_created_gmt:
          type: string
          format: date-time
          description: The date the order was created, as GMT.
          readOnly: true
        date_modified:
          type: string
          format: date-time
          description: The date the order was last modified, in the site's timezone.
          readOnly: true
        date_modified_gmt:
          type: string
          format: date-time
          description: The date the order was last modified, as GMT.
          readOnly: true
        discount_total:
          type: string
          description: Total discount amount for the order.
          readOnly: true
        discount_tax:
          type: string
          description: Total discount tax amount for the order.
          readOnly: true
        shipping_total:
          type: string
          description: Total shipping amount for the order.
          readOnly: true
        shipping_tax:
          type: string
          description: Total shipping tax amount for the order.
          readOnly: true
        cart_tax:
          type: string
          description: Sum of line item taxes only.
          readOnly: true
        total:
          type: string
          description: Grand total.
          readOnly: true
        total_tax:
          type: string
          description: Sum of all taxes.
          readOnly: true
        prices_include_tax:
          type: boolean
          description: True if prices included tax during checkout.
          readOnly: true
        customer_id:
          type: integer
          description: User ID who owns the order. 0 for guests.
          default: 0
        customer_ip_address:
          type: string
          description: Customer's IP address.
          readOnly: true
        customer_user_agent:
          type: string
          description: User agent of the customer.
          readOnly: true
        customer_note:
          type: string
          description: Note left by customer during checkout.
        billing:
          $ref: '#/components/schemas/Billing'
        shipping:
          $ref: '#/components/schemas/Shipping'
        payment_method:
          type: string
          description: Payment method ID.
        payment_method_title:
          type: string
          description: Payment method title.
        transaction_id:
          type: string
          description: Unique transaction ID.
        date_paid:
          type: string
          format: date-time
          description: The date the order was paid, in the site's timezone.
          readOnly: true
        date_paid_gmt:
          type: string
          format: date-time
          description: The date the order was paid, as GMT.
          readOnly: true
        date_completed:
          type: string
          format: date-time
          description: The date the order was completed, in the site's timezone.
          readOnly: true
        date_completed_gmt:
          type: string
          format: date-time
          description: The date the order was completed, as GMT.
          readOnly: true
        cart_hash:
          type: string
          description: MD5 hash of cart items to ensure orders are not modified.
          readOnly: true
        meta_data:
          type: array
          items:
            $ref: '#/components/schemas/Meta'
        line_items:
          type: array
          items:
            $ref: '#/components/schemas/LineItem'
        tax_lines:
          type: array
          items:
            $ref: '#/components/schemas/TaxLine'
        shipping_lines:
          type: array
          items:
            $ref: '#/components/schemas/ShippingLine'
        fee_lines:
          type: array
          items:
            $ref: '#/components/schemas/FeeLine'
        coupon_lines:
          type: array
          items:
            $ref: '#/components/schemas/CouponLine'
        refunds:
          type: array
          items:
            $ref: '#/components/schemas/Refund'
        set_paid:
          type: boolean
          description: Define if the order is paid. It will set the status to processing and reduce stock items.
          default: false
          writeOnly: true
    Billing:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        company:
          type: string
        address_1:
          type: string
        address_2:
          type: string
        city:
          type: string
        state:
          type: string
        postcode:
          type: string
        country:
          type: string
        email:
          type: string
        phone:
          type: string
    Shipping:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        company:
          type: string
        address_1:
          type: string
        address_2:
          type: string
        city:
          type: string
        state:
          type: string
        postcode:
          type: string
        country:
          type: string
    Meta:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        key:
          type: string
        value:
          type: string
    LineItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        product_id:
          type: integer
        variation_id:
          type: integer
        quantity:
          type: integer
        tax_class:
          type: string
        subtotal:
          type: string
        subtotal_tax:
          type: string
          readOnly: true
        total:
          type: string
        total_tax:
          type: string
          readOnly: true
        taxes:
          type: array
          items:
            $ref: '#/components/schemas/Tax'
        meta_data:
          type: array
          items:
            $ref: '#/components/schemas/Meta'
        sku:
          type: string
          readOnly: true
        price:
          type: string
          readOnly: true
    TaxLine:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        rate_code:
          type: string
          readOnly: true
        rate_id:
          type: string
          readOnly: true
        label:
          type: string
          readOnly: true
        compound:
          type: boolean
          readOnly: true
        tax_total:
          type: string
          readOnly: true
        shipping_tax_total:
          type: string
          readOnly: true
        meta_data:
          type: array
          items:
            $ref: '#/components/schemas/Meta'
    ShippingLine:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        method_title:
          type: string
        method_id:
          type: string
        total:
          type: string
        total_tax:
          type: string
          readOnly: true
        taxes:
          type: array
          items:
            $ref: '#/components/schemas/Tax'
        meta_data:
          type: array
          items:
            $ref: '#/components/schemas/Meta'
    FeeLine:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        tax_class:
          type: string
        tax_status:
          type: string
          enum:
            - taxable
            - none
        total:
          type: string
        total_tax:
          type: string
          readOnly: true
        taxes:
          type: array
          items:
            $ref: '#/
