openapi: 3.0.3
info:
  title: WooCommerce Orders API
  description: This is a sample API for WooCommerce order retrieval.
  version: 1.0.0
servers:
  - url: https://example.com/wp-json/wc/v3

paths:
  /wp-json/wc/v3/orders/{id}:
    get:
      summary: Retrieve Order
      description: Retrieve an order by ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the order to retrieve
      responses:
        '200':
          description: Order retrieved successfully
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/components/schemas/Order'
        '404':
          description: Order not found
